.TH kylin-video 1 "19 June 2017" "The Kylin Video Project" "Kylin Video"
.SH NAME
kylin-video \- The best GUI frontend for MPlayer
.SH SYNOPSIS
.B kylin-video
.SH DESCRIPTION
.TP
Kylin Video is a GUI media player based on Qt 5, using \fBmplayer\fR(1) as its backend.
.PP
.SH SEE ALSO
\fBmplayer\fR(1)
.SH AUTHOR
The author of Kylin Video is lixiang <lixiang@kylinos.cn>.

This manual page was written by lixiang <lixiang@kylinos.cn> for the
Kylin project (but may be used by others).

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 or any later
version published by the Free Software Foundation. On Debian systems, the
complete text of the GNU General Public License can be found in
\fB/usr/share/common-licenses/GPL\fR.

.SH BUGS
Please submit bugs to \fBhttps://github.com/ukui/kylin-video/issues\fR.
